name: Build Windows EXE

on: 
  workflow_dispatch: # Hiermee kun je het ook handmatig starten
  push:

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        pip install pyinstaller plyer
    - name: Build EXE
      run: |
        pyinstaller --noconsole --onefile --hidden-import plyer.platforms.win.notification ev_lader_dark.py
    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: EV-Charger-Programma
        path: dist/ev_lader_dark.exe
